version: "3.8"

services:
  api:
    container_name: fpiBackend
    image: 434807866199.dkr.ecr.eu-west-3.amazonaws.com/oei-backend:latest
    env_file:
      - .env.prod
    ports:
      - "3001:3001"
    # No depend_on, la infraestructura se gestiona fuera (RDS, ElastiCache)
