AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC + RDS PostgreSQL + Redis ElastiCache + ECS Fargate Service"

Parameters:
  DBUser:
    Type: String
    Default: OeiUser
    Description: master user for database
  DBPassword:
    Type: String
    NoEcho: true
    Description: master password
  DBName:
    Type: String
    Default: oeidb
    Description: database name
  ContainerImage:
    Type: String
    Default: 434807866199.dkr.ecr.us-east-1.amazonaws.com/backend-oei:latest
    Description: Docker image URI en ECR
Resources:
  ## --------------------------
  ## VPC
  ## --------------------------
  OeiVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: oei-vpc

  OeiInternetGateway:
    Type: AWS::EC2::InternetGateway

  OeiVpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref OeiVpc
      InternetGatewayId: !Ref OeiInternetGateway

  ## --------------------------
  ## Subnets
  ## --------------------------
  OeiPublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OeiVpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Oei-public-subnet-a

  OeiPublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OeiVpc
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Oei-public-subnet-b

  OeiPrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OeiVpc
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Oei-private-subnet-a

  OeiPrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OeiVpc
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Oei-private-subnet-b

  ## --------------------------
  ## Routing
  ## --------------------------
  OeiPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref OeiVpc

  OeiPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref OeiPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref OeiInternetGateway

  OeiPublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref OeiPublicSubnetA
      RouteTableId: !Ref OeiPublicRouteTable

  OeiPublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref OeiPublicSubnetB
      RouteTableId: !Ref OeiPublicRouteTable

  ## --------------------------
  ## Security Groups
  ## --------------------------
  OeiALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      VpcId: !Ref OeiVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  OeiRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      VpcId: !Ref OeiVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16

  OeiRedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Redis Security Group
      VpcId: !Ref OeiVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 10.0.0.0/16

  OeiECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Service SG
      VpcId: !Ref OeiVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3001
          ToPort: 3001
          CidrIp: 0.0.0.0/0

  ## --------------------------
  ## RDS PostgreSQL
  ## --------------------------
  OeiPostgresSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref OeiPrivateSubnetA
        - !Ref OeiPrivateSubnetB

  OeiPostgres:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: oei-postgres
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: "16.4"
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref OeiRDSSecurityGroup
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref OeiPostgresSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      StorageType: gp2
      DeletionProtection: false

  ## --------------------------
  ## Redis ElastiCache
  ## --------------------------
  OeiRedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for Redis
      SubnetIds:
        - !Ref OeiPrivateSubnetA
        - !Ref OeiPrivateSubnetB

  OeiRedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: oei-redis
      Engine: redis
      CacheNodeType: cache.t3.micro
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - !Ref OeiRedisSecurityGroup
      CacheSubnetGroupName: !Ref OeiRedisSubnetGroup

  ## --------------------------
  ## CloudWatch Logs
  ## --------------------------
  OeiBackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/backend-oei
      RetentionInDays: 14
  ## --------------------------
  ## IAM Roles ECS
  ## --------------------------
  ECSExecUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ecs-exec-cli-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ssmmessages:CreateControlChannel
              - ssmmessages:CreateDataChannel
              - ssmmessages:OpenControlChannel
              - ssmmessages:OpenDataChannel
              - ssm:StartSession
              - ssm:DescribeSessions
              - ssm:TerminateSession
            Resource: "*"
      Users:
        - Anibalrvr
  OeiECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: oei-ecs-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: ECSSecretsManagerAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource:
                  - arn:aws:secretsmanager:us-east-1:434807866199:secret:jwt-private-key-*
                  - arn:aws:secretsmanager:us-east-1:434807866199:secret:jwt-public-key-*
  OeiECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: oei-ecs-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess

  ## --------------------------
  ## ECS + ALB
  ## --------------------------
  OeiCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: oei-cluster
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT

  OeiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: oei-task
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt OeiECSExecutionRole.Arn
      TaskRoleArn: !GetAtt OeiECSTaskRole.Arn
      ContainerDefinitions:
        - Name: backend-oei
          Image: !Ref ContainerImage
          Essential: true
          PortMappings:
            - ContainerPort: 3001
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: PORT
              Value: "3001"
            - Name: DATABASE_URL
              Value: !Sub "postgresql://${DBUser}:${DBPassword}@${OeiPostgres.Endpoint.Address}:5432/${DBName}"
            - Name: REDIS_HOST
              Value: !GetAtt OeiRedisCluster.RedisEndpoint.Address
            - Name: REDIS_PORT
              Value: "6379"
            - Name: REDIS_URL
              Value: !Sub "redis://${OeiRedisCluster.RedisEndpoint.Address}:6379"
            - Name: REDIS
              Value: !Sub "redis://${OeiRedisCluster.RedisEndpoint.Address}:6379"
          Secrets:
            - Name: JWT_PRIVATE_KEY
              ValueFrom: arn:aws:secretsmanager:us-east-1:434807866199:secret:jwt-private-key-s8NuYB
            - Name: JWT_PUBLIC_KEY
              ValueFrom: arn:aws:secretsmanager:us-east-1:434807866199:secret:jwt-public-key-ThJgXn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/backend-oei
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  OeiListenerHttps:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref OeiALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:434807866199:certificate/cb650945-1cf3-4040-83cb-ce93103ac4e0
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref OeiTargetGroup
  OeiALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: oei-alb
      Subnets:
        - !Ref OeiPublicSubnetA
        - !Ref OeiPublicSubnetB
      SecurityGroups:
        - !Ref OeiECSSecurityGroup
        - !Ref OeiALBSecurityGroup
      Scheme: internet-facing
      Type: application

  OeiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: oei-target
      Port: 3001
      Protocol: HTTP
      VpcId: !Ref OeiVpc
      TargetType: ip
      HealthCheckPath: /api/health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Matcher:
        HttpCode: "200-399"

  OeiListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref OeiALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref OeiTargetGroup

  OeiService:
    Type: AWS::ECS::Service
    DependsOn:
      - OeiListener
      - OeiTargetGroup
      - OeiBackendLogGroup
    Properties:
      ServiceName: oei-service
      Cluster: !Ref OeiCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref OeiTaskDefinition
      HealthCheckGracePeriodSeconds: 360
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref OeiPublicSubnetA
            - !Ref OeiPublicSubnetB
          SecurityGroups:
            - !Ref OeiECSSecurityGroup
      LoadBalancers:
        - ContainerName: backend-oei
          ContainerPort: 3001
          TargetGroupArn: !Ref OeiTargetGroup

Outputs:
  RDSEndpoint:
    Description: RDS endpoint
    Value: !GetAtt OeiPostgres.Endpoint.Address
  RedisEndpoint:
    Description: Redis endpoint
    Value: !GetAtt OeiRedisCluster.RedisEndpoint.Address
  ALBEndpoint:
    Description: Public ALB DNS
    Value: !GetAtt OeiALB.DNSName



