export enum PermissionEnum {
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  VIEW_DASHBOARD_ATTENDANCE = "VIEW_DASHBOARD_ATTENDANCE",
  VIEW_DASHBOARD_EVALUATION = "VIEW_DASHBOARD_EVALUATION",
  VIEW_DASHBOARD_MENTORING = "VIEW_DASHBOARD_MENTORING",
  VIEW_DASHBOARD_PARTICIPANTS = "VIEW_DASHBOARD_PARTICIPANTS",
  VIEW_GROUPS = "VIEW_GROUPS",
  VIEW_ATTENDANCE = "VIEW_ATTENDANCE",
  VIEW_MENTORING = "VIEW_MENTORING",
  VIEW_CATALOGUES = "VIEW_CATALOGUES",
  VIEW_CATALOGUE_SCHOOL = "VIEW_CATALOGUE_SCHOOL",
  VIEW_CATALOGUE_MODULE = "VIEW_CATALOGUE_MODULE",
  VIEW_CATALOGUE_ZONE = "VIEW_CATALOGUE_ZONE"
}
