export declare enum PermissionEnum {
    VIEW_DASHBOARD = "VIEW_DASHBOARD",
    VIEW_GROUPS = "VIEW_GROUPS",
    VIEW_ATTENDANCE = "VIEW_ATTENDANCE",
    VIEW_CATALOGUES = "VIEW_CATALOGUES",
    VIEW_CATALOGUE_SCHOOL = "VIEW_CATALOGUE_SCHOOL",
    VIEW_CATALOGUE_ZONE = "VIEW_CATALOGUE_ZONE"
}
