export enum PermissionEnum {
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  VIEW_GROUPS = "VIEW_GROUPS",
  CREATE_GROUPS = "CREATE_GROUPS",
  EDIT_GROUPS = "EDIT_GROUPS",
  DELETE_GROUPS = "DELETE_GROUPS",
  VIEW_CATALOGUES = "VIEW_CATALOGUES",
  VIEW_CATALOGUE_SCHOOL = "VIEW_CATALOGUE_SCHOOL",
  VIEW_CATALOGUE_ZONE = "VIEW_CATALOGUE_ZONE"
}
