export const menuJson = {
  dashboard: "/admin/dashboard",
  grupos: "/admin/grupos",
  evaluaciones: "/admin/evaluaciones",
  autoEvaluacion: "/admin/evaluaciones/auto-evaluación",
  portafolio: "/admin/evaluaciones/portafolio",
  diagnostico: "/admin/evaluaciones/diagnostico",
  asistencia: "/admin/asistencia",
  talleres: "/admin/asistencia/talleres",
  seminarios: "/admin/asistencia/seminarios",
  comunidadesPractica: "/admin/asistencia/comunidades-practica",
  sesionesSincronicas: "/admin/asistencia/sesiones-sincronicas",
  mentorias: "/admin/asistencia/mentorias",
  triplePerfil: "/admin/triple-perfil",
  formadores: "/admin/triple-perfil/formadores",
  mentores: "/admin/triple-perfil/mentores",
  tecnicosApoyo: "/admin//triple-perfil/tecnicos-apoyo",
  docentes: "/admin/docentes",
  catalogos: "/admin/catalogos",
  centrosEscolares: "/admin/catalogo/centros-escolares",
  zonas: "/admin/catalogo/zonas"
};
