export const menuJson = {
  dashboard: "/admin/dashboard",
  asistenciaDashboard: "/admin/dashboard/asistencia",
  evaluacionDashboard: "/admin/dashboard/evaluacion",
  mentoriaDashboard: "/admin/dashboard/mentoria",
  participantesDashboard: "/admin/dashboard/participantes",
  grupos: "/admin/grupos",
  asistencia: "/admin/asistencia",
  mentoria: "/admin/mentoria",
  catalogos: "/admin/catalogo",
  modulos: "/admin/catalogo/modulos-formativos",
  centrosEscolares: "/admin/catalogo/centros-escolares",
  zonas: "/admin/catalogo/zonas",
  triplePerfil: "/admin/triple-perfil",
  formadores: "/admin/triple-perfil/formadores",
  mentores: "/admin/triple-perfil/mentores",
  tecnicosApoyo: "/admin/triple-perfil/tecnicos-apoyo",
  docentes: "/admin/docentes",
  evaluaciones: "/admin/evaluaciones",
  autoEvaluacion: "/admin/evaluaciones/auto-evaluación",
  portafolio: "/admin/evaluaciones/portafolio",
  diagnostico: "/admin/evaluaciones/diagnostico"
};
