export const personData = [
  {
    firstName: "Juan Luis",
    lastName1: "Arregui",
    lastName2: "Córdoba",
    dui: "87000000-0",
    address: "Vial de Florencio Redondo 9 Apt. 90 ",
    gender: "F",
    phoneNumber: "64044545",
    birthdate: "1999-03-21",
    districtId: 3,
    typePersonId: 4,
    career: "Engineer, manufacturing",
    nip: "1234",
    email: "ale15@yahoo.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Mohamed",
    lastName1: "Olivera",
    lastName2: "Sandoval",
    dui: "87000001-0",
    address: "Calle Malena Viña 95",
    gender: "F",
    phoneNumber: "61911407",
    birthdate: "1997-08-21",
    districtId: 3,
    typePersonId: 4,
    career: "Forensic psychologist",
    nip: "1235",
    email: "diegoherberto@tellez.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Ariel",
    lastName1: "Cuenca",
    lastName2: "Cárdenas",
    dui: "87000002-0",
    address: "Urbanización de Galo Daza 54",
    gender: "M",
    phoneNumber: "63354206",
    birthdate: "1999-04-27",
    districtId: 3,
    typePersonId: 4,
    career: "Information systems manager",
    nip: "1236",
    email: "rodrigoquerol@chacon.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Jose Luis",
    lastName1: "Goñi",
    lastName2: "Infante",
    dui: "87000003-0",
    address: "Cuesta Ángela Solís 26",
    gender: "M",
    phoneNumber: "64517946",
    birthdate: "1988-04-12",
    districtId: 3,
    typePersonId: 4,
    career: "Plant breeder/geneticist",
    nip: "1237",
    email: "gimenoliliana@gmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Alfonso",
    lastName1: "Maestre",
    lastName2: "Sales",
    dui: "87000004-0",
    address: "Plaza de Jonatan Olmo 75",
    gender: "F",
    phoneNumber: "65761033",
    birthdate: "1993-05-24",
    districtId: 3,
    typePersonId: 4,
    career: "Economist",
    nip: "1238",
    email: "bcollado@yahoo.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Teodoro",
    lastName1: "Pedrero",
    lastName2: "Navas",
    dui: "87000005-0",
    address: "Paseo de Salvador Porcel 23 Apt. 57 ",
    gender: "F",
    phoneNumber: "68657358",
    birthdate: "1994-03-05",
    districtId: 3,
    typePersonId: 4,
    career: "Sport and exercise psychologist",
    nip: "1239",
    email: "corona46@hotmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Ainoa",
    lastName1: "Castro",
    lastName2: "Ibáñez",
    dui: "87000006-0",
    address: "Via de Rodrigo Mateu 20",
    gender: "F",
    phoneNumber: "63177096",
    birthdate: "1989-12-20",
    districtId: 3,
    typePersonId: 4,
    career: "Designer, ceramics/pottery",
    nip: "1240",
    email: "emiliopedrero@yahoo.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Nando",
    lastName1: "Rovira",
    lastName2: "Barberá",
    dui: "87000007-0",
    address: "Urbanización de Eduardo Izquierdo 10",
    gender: "F",
    phoneNumber: "69016880",
    birthdate: "1991-01-30",
    districtId: 3,
    typePersonId: 4,
    career: "Scientist, research (medical)",
    nip: "1241",
    email: "ortegajuan-antonio@villalobos.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Olalla",
    lastName1: "Miró",
    lastName2: "Martinez",
    dui: "87000008-0",
    address: "Cañada de Norberto Aguado 291 Piso 4 ",
    gender: "F",
    phoneNumber: "63049208",
    birthdate: "1995-04-09",
    districtId: 3,
    typePersonId: 4,
    career: "Public relations account executive",
    nip: "1242",
    email: "gracianomoya@hotmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Berta",
    lastName1: "Blanco",
    lastName2: "Barrena",
    dui: "87000009-0",
    address: "Cañada Marcelino Mas 45",
    gender: "F",
    phoneNumber: "69574247",
    birthdate: "1993-05-30",
    districtId: 3,
    typePersonId: 4,
    career: "Microbiologist",
    nip: "1243",
    email: "nbatlle@yahoo.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Perlita",
    lastName1: "Torrent",
    lastName2: "Llabrés",
    dui: "87000010-0",
    address: "Calle de Dorotea Pou 904",
    gender: "M",
    phoneNumber: "64711553",
    birthdate: "1992-05-21",
    districtId: 3,
    typePersonId: 5,
    career: "Trade union research officer",
    nip: "1244",
    email: "floresalbano@baez-amor.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Juan Antonio",
    lastName1: "Mendoza",
    lastName2: "Águila",
    dui: "87000011-0",
    address: "Cañada Aurelia Palacios 85",
    gender: "M",
    phoneNumber: "66489168",
    birthdate: "1990-10-23",
    districtId: 3,
    typePersonId: 5,
    career: "Curator",
    nip: "1245",
    email: "dionisiaconde@arregui.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Abraham",
    lastName1: "Jaume",
    lastName2: "Ribas",
    dui: "87000012-0",
    address: "Calle de Dulce Alegria 86",
    gender: "M",
    phoneNumber: "63241670",
    birthdate: "1993-04-03",
    districtId: 3,
    typePersonId: 5,
    career: "Clinical embryologist",
    nip: "1246",
    email: "evelia52@cabezas-casals.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Juan Francisco",
    lastName1: "Quintero",
    lastName2: "Pacheco",
    dui: "87000013-0",
    address: "Pasadizo de María Jesús Bayón 40 Apt. 73 ",
    gender: "F",
    phoneNumber: "65776133",
    birthdate: "1995-04-20",
    districtId: 3,
    typePersonId: 5,
    career: "Counselling psychologist",
    nip: "1247",
    email: "patricia71@yahoo.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Arturo",
    lastName1: "Quevedo",
    lastName2: "Galvez",
    dui: "87000014-0",
    address: "Cuesta Eric Molina 2 Piso 4 ",
    gender: "M",
    phoneNumber: "69294213",
    birthdate: "1993-08-20",
    districtId: 3,
    typePersonId: 5,
    career: "Garment/textile technologist",
    nip: "1248",
    email: "leonmartin@hotmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Nico",
    lastName1: "Avilés",
    lastName2: "Roldán",
    dui: "87000015-0",
    address: "Vial Eladio Chaparro 396 Apt. 95 ",
    gender: "F",
    phoneNumber: "62391176",
    birthdate: "1987-02-01",
    districtId: 3,
    typePersonId: 5,
    career: "Health service manager",
    nip: "1249",
    email: "eherranz@borja.es",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Galo",
    lastName1: "Ortega",
    lastName2: "Boada",
    dui: "87000016-0",
    address: "Camino Obdulia Carretero 1 Puerta 7 ",
    gender: "F",
    phoneNumber: "63410138",
    birthdate: "1988-01-28",
    districtId: 3,
    typePersonId: 5,
    career: "Administrator, local government",
    nip: "1250",
    email: "nvives@llado.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Alcides",
    lastName1: "Doménech",
    lastName2: "Baena",
    dui: "87000017-0",
    address: "Ronda de Rosa María Prado 82 Piso 6 ",
    gender: "M",
    phoneNumber: "63937634",
    birthdate: "1990-04-24",
    districtId: 3,
    typePersonId: 5,
    career: "Personnel officer",
    nip: "1251",
    email: "hroman@ruiz.es",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Carlos",
    lastName1: "Ibarra",
    lastName2: "Nogueira",
    dui: "87000018-0",
    address: "Alameda de Aránzazu Hernández 11",
    gender: "F",
    phoneNumber: "63752523",
    birthdate: "1987-11-21",
    districtId: 3,
    typePersonId: 5,
    career: "Conservation officer, historic buildings",
    nip: "1252",
    email: "opoza@gmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Asunción",
    lastName1: "Arnal",
    lastName2: "Perelló",
    dui: "87000019-0",
    address: "Callejón Reina Parra 265 Apt. 46 ",
    gender: "F",
    phoneNumber: "67954930",
    birthdate: "1985-05-16",
    districtId: 3,
    typePersonId: 5,
    career: "Production engineer",
    nip: "1253",
    email: "rogelio93@yahoo.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Claudio",
    lastName1: "Morata",
    lastName2: "Pomares",
    dui: "87000020-0",
    address: "Glorieta Carmelo Grande 79 Apt. 58 ",
    gender: "M",
    phoneNumber: "69236587",
    birthdate: "1986-01-04",
    districtId: 3,
    typePersonId: 6,
    career: "Retail merchandiser",
    nip: "1254",
    email: "roman33@hotmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Concha",
    lastName1: "Acuña",
    lastName2: "Blanco",
    dui: "87000021-0",
    address: "Glorieta de Alfonso Quintanilla 6 Piso 1 ",
    gender: "M",
    phoneNumber: "64568394",
    birthdate: "1995-05-13",
    districtId: 3,
    typePersonId: 6,
    career: "Volunteer coordinator",
    nip: "1255",
    email: "celso80@hotmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Perlita",
    lastName1: "Aguilera",
    lastName2: "Ojeda",
    dui: "87000022-0",
    address: "Pasaje Diego Alsina 7",
    gender: "M",
    phoneNumber: "67707029",
    birthdate: "1990-06-21",
    districtId: 3,
    typePersonId: 6,
    career: "Teacher, music",
    nip: "1256",
    email: "gguerrero@gmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Camilo",
    lastName1: "Tejedor",
    lastName2: "Chacón",
    dui: "87000023-0",
    address: "Pasaje Graciana Marquez 42 Apt. 90 ",
    gender: "F",
    phoneNumber: "67624214",
    birthdate: "1996-03-08",
    districtId: 3,
    typePersonId: 6,
    career: "Therapist, drama",
    nip: "1257",
    email: "custodiaprat@andres.net",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Prudencio",
    lastName1: "Matas",
    lastName2: "Pablo",
    dui: "87000024-0",
    address: "C. de Elvira León 22",
    gender: "F",
    phoneNumber: "69659689",
    birthdate: "1986-07-16",
    districtId: 3,
    typePersonId: 6,
    career: "Therapist, art",
    nip: "1258",
    email: "hidalgonoelia@ferrero.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Alicia",
    lastName1: "Contreras",
    lastName2: "Larrañaga",
    dui: "87000025-0",
    address: "Calle Jose Antonio Pombo 34",
    gender: "F",
    phoneNumber: "67329769",
    birthdate: "1989-01-17",
    districtId: 3,
    typePersonId: 6,
    career: "Surgeon",
    nip: "1259",
    email: "morabaudelio@ortega-peralta.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Noa",
    lastName1: "Carpio",
    lastName2: "Mayoral",
    dui: "87000026-0",
    address: "Plaza de Maristela Sanz 74 Piso 5 ",
    gender: "M",
    phoneNumber: "64385569",
    birthdate: "1992-09-11",
    districtId: 3,
    typePersonId: 6,
    career: "Bookseller",
    nip: "1260",
    email: "edelmiro31@ribes.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Armando",
    lastName1: "Delgado",
    lastName2: "Pi",
    dui: "87000027-0",
    address: "Avenida Liliana Sacristán 15 Puerta 5 ",
    gender: "F",
    phoneNumber: "64053082",
    birthdate: "1993-01-10",
    districtId: 3,
    typePersonId: 6,
    career: "Electrical engineer",
    nip: "1261",
    email: "batllesoledad@hotmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Isaura",
    lastName1: "Francisco",
    lastName2: "Romeu",
    dui: "87000028-0",
    address: "Cuesta de Jose Miguel Correa 70",
    gender: "F",
    phoneNumber: "62284071",
    birthdate: "1997-03-07",
    districtId: 3,
    typePersonId: 6,
    career: "Psychiatric nurse",
    nip: "1262",
    email: "gracielaibanez@gmail.com",
    passwd: "Qazwsx123",
    roleId: 1
  },
  {
    firstName: "Santos",
    lastName1: "Mate",
    lastName2: "Sáez",
    dui: "87000029-0",
    address: "Paseo de Fortunata Fonseca 3",
    gender: "M",
    phoneNumber: "64339045",
    birthdate: "1987-02-15",
    districtId: 3,
    typePersonId: 6,
    career: "Producer, television/film/video",
    nip: "1263",
    email: "maricelagonzalo@amador.es",
    passwd: "Qazwsx123",
    roleId: 1
  }
];
